/** Permission names matching backend PermissionConstants. */
export const PERMISSIONS = {
  Dashboard: {
    View: 'Dashboard.View',
  },
  Catalog: {
    Categories: {
      View: 'Catalog.Categories.View',
      Create: 'Catalog.Categories.Create',
      Edit: 'Catalog.Categories.Edit',
      Delete: 'Catalog.Categories.Delete',
    },
    Collections: {
      View: 'Catalog.Collections.View',
      Create: 'Catalog.Collections.Create',
      Edit: 'Catalog.Collections.Edit',
      Delete: 'Catalog.Collections.Delete',
    },
    Products: {
      View: 'Catalog.Products.View',
      Create: 'Catalog.Products.Create',
      Edit: 'Catalog.Products.Edit',
      Delete: 'Catalog.Products.Delete',
      Import: 'Catalog.Products.Import',
      Export: 'Catalog.Products.Export',
    },
    Inventory: {
      View: 'Catalog.Inventory.View',
      Create: 'Catalog.Inventory.Create',
      Edit: 'Catalog.Inventory.Edit',
      Delete: 'Catalog.Inventory.Delete',
      Import: 'Catalog.Inventory.Import',
      Export: 'Catalog.Inventory.Export',
      ManageCodes: 'Catalog.Inventory.ManageCodes',
      ViewCosts: 'Catalog.Inventory.ViewCosts',
      ManageBatches: 'Catalog.Inventory.ManageBatches',
      ManageSuppliers: 'Catalog.Inventory.ManageSuppliers',
      RevealCodes: 'Catalog.Inventory.RevealCodes',
    },
  },
  Orders: {
    View: 'Orders.View',
    Edit: 'Orders.Edit',
    Refund: 'Orders.Refund',
  },
  Customers: {
    View: 'Customers.View',
    Edit: 'Customers.Edit',
  },
  Users: {
    View: 'Users.View',
    Edit: 'Users.Edit',
    AssignRoles: 'Users.AssignRoles',
  },
  Roles: {
    View: 'Roles.View',
    Create: 'Roles.Create',
    Edit: 'Roles.Edit',
    Delete: 'Roles.Delete',
    AssignUsers: 'Roles.AssignUsers',
  },
  Permissions: {
    View: 'Permissions.View',
  },
  Memberships: {
    View: 'Memberships.View',
    Create: 'Memberships.Create',
    Edit: 'Memberships.Edit',
    Delete: 'Memberships.Delete',
    Assign: 'Memberships.Assign',
    Renew: 'Memberships.Renew',
    Cancel: 'Memberships.Cancel',
    ConfigureBenefits: 'Memberships.ConfigureBenefits',
  },
  Promotions: {
    View: 'Promotions.View',
    Create: 'Promotions.Create',
    Edit: 'Promotions.Edit',
    Delete: 'Promotions.Delete',
    Publish: 'Promotions.Publish',
  },
  Coupons: {
    View: 'Coupons.View',
    Create: 'Coupons.Create',
    Edit: 'Coupons.Edit',
    Delete: 'Coupons.Delete',
    Generate: 'Coupons.Generate',
    Export: 'Coupons.Export',
    Import: 'Coupons.Import',
  },
  Themes: {
    View: 'Themes.View',
    Create: 'Themes.Create',
    Edit: 'Themes.Edit',
    Delete: 'Themes.Delete',
    Publish: 'Themes.Publish',
    Schedule: 'Themes.Schedule',
    Assign: 'Themes.Assign',
    Export: 'Themes.Export',
    Import: 'Themes.Import',
    Rollback: 'Themes.Rollback',
  },
  Campaigns: {
    View: 'Campaigns.View',
    Create: 'Campaigns.Create',
    Edit: 'Campaigns.Edit',
    Publish: 'Campaigns.Publish',
    Delete: 'Campaigns.Delete',
  },
  PageBuilder: {
    View: 'PageBuilder.View',
    Edit: 'PageBuilder.Edit',
    Publish: 'PageBuilder.Publish',
  },
  Legal: {
    View: 'Legal.View',
    Create: 'Legal.Create',
    Edit: 'Legal.Edit',
    Publish: 'Legal.Publish',
    Delete: 'Legal.Delete',
  },
  Suppliers: {
    View: 'Suppliers.View',
    Create: 'Suppliers.Create',
    Edit: 'Suppliers.Edit',
    Delete: 'Suppliers.Delete',
    ManageMappings: 'Suppliers.ManageMappings',
  },
  Security: {
    View: 'Security.View',
    ManageUsers: 'Security.ManageUsers',
    ManageEmails: 'Security.ManageEmails',
    ManageCountries: 'Security.ManageCountries',
    ManageIPs: 'Security.ManageIPs',
    ViewEvents: 'Security.ViewEvents',
    ManageAlerts: 'Security.ManageAlerts',
    ManageDevices: 'Security.ManageDevices',
  },
  Reviews: {
    View: 'Reviews.View',
    Moderate: 'Reviews.Moderate',
  },
  Notifications: {
    View: 'Notifications.View',
    Send: 'Notifications.Send',
  },
  Referral: {
    View: 'Referral.View',
    Manage: 'Referral.Manage',
  },
  Reports: {
    View: 'Reports.View',
    Export: 'Reports.Export',
    Schedule: 'Reports.Schedule',
    Delete: 'Reports.Delete',
  },
  Localization: {
    Manage: 'Localization.Manage',
  },
  Settings: {
    View: 'Settings.View',
    Edit: 'Settings.Edit',
  },
  Support: {
    View: 'Support.View',
    Manage: 'Support.Manage',
    Create: 'Support.Create',
    Reply: 'Support.Reply',
    Assign: 'Support.Assign',
    Close: 'Support.Close',
    Delete: 'Support.Delete',
    ManageCategories: 'Support.ManageCategories',
    ManageSavedReplies: 'Support.ManageSavedReplies',
    ManageKnowledgeBase: 'Support.ManageKnowledgeBase',
    ViewAnalytics: 'Support.ViewAnalytics',
  },
  Media: {
    Upload: 'Media.Upload',
    Delete: 'Media.Delete',
  },
  AuditLogs: {
    View: 'AuditLogs.View',
  },
  Operations: {
    View: 'Operations.View',
    Manage: 'Operations.Manage',
    Retry: 'Operations.Retry',
    Export: 'Operations.Export',
    Clear: 'Operations.Clear',
  },
  Analytics: {
    View: 'Analytics.View',
    Export: 'Analytics.Export',
    Compare: 'Analytics.Compare',
    Manage: 'Analytics.Manage',
  },
  Communication: {
    View: 'Communication.View',
    Manage: 'Communication.Manage',
    Send: 'Communication.Send',
    ManageTemplates: 'Communication.ManageTemplates',
    ManageProviders: 'Communication.ManageProviders',
  },
  Faq: {
    View: 'Faq.View',
    Create: 'Faq.Create',
    Edit: 'Faq.Edit',
    Delete: 'Faq.Delete',
    Publish: 'Faq.Publish',
  },
  WhatsAppBot: {
    View: 'WhatsAppBot.View',
    Edit: 'WhatsAppBot.Edit',
  },
} as const;

export const ALL_PERMISSIONS: readonly string[] = [
  PERMISSIONS.Dashboard.View,
  PERMISSIONS.Catalog.Categories.View,
  PERMISSIONS.Catalog.Categories.Create,
  PERMISSIONS.Catalog.Categories.Edit,
  PERMISSIONS.Catalog.Categories.Delete,
  PERMISSIONS.Catalog.Products.View,
  PERMISSIONS.Catalog.Products.Create,
  PERMISSIONS.Catalog.Products.Edit,
  PERMISSIONS.Catalog.Products.Delete,
  PERMISSIONS.Catalog.Products.Import,
  PERMISSIONS.Catalog.Products.Export,
  PERMISSIONS.Catalog.Inventory.View,
  PERMISSIONS.Catalog.Inventory.Create,
  PERMISSIONS.Catalog.Inventory.Edit,
  PERMISSIONS.Catalog.Inventory.Delete,
  PERMISSIONS.Catalog.Inventory.Import,
  PERMISSIONS.Catalog.Inventory.Export,
  PERMISSIONS.Catalog.Inventory.ManageCodes,
  PERMISSIONS.Catalog.Inventory.ViewCosts,
  PERMISSIONS.Catalog.Inventory.ManageBatches,
  PERMISSIONS.Catalog.Inventory.ManageSuppliers,
  PERMISSIONS.Catalog.Inventory.RevealCodes,
  PERMISSIONS.Orders.View,
  PERMISSIONS.Orders.Edit,
  PERMISSIONS.Orders.Refund,
  PERMISSIONS.Customers.View,
  PERMISSIONS.Customers.Edit,
  PERMISSIONS.Users.View,
  PERMISSIONS.Users.Edit,
  PERMISSIONS.Users.AssignRoles,
  PERMISSIONS.Roles.View,
  PERMISSIONS.Roles.Create,
  PERMISSIONS.Roles.Edit,
  PERMISSIONS.Roles.Delete,
  PERMISSIONS.Roles.AssignUsers,
  PERMISSIONS.Permissions.View,
  PERMISSIONS.Memberships.View,
  PERMISSIONS.Memberships.Create,
  PERMISSIONS.Memberships.Edit,
  PERMISSIONS.Memberships.Delete,
  PERMISSIONS.Memberships.Assign,
  PERMISSIONS.Memberships.Renew,
  PERMISSIONS.Memberships.Cancel,
  PERMISSIONS.Memberships.ConfigureBenefits,
  PERMISSIONS.Promotions.View,
  PERMISSIONS.Promotions.Create,
  PERMISSIONS.Promotions.Edit,
  PERMISSIONS.Promotions.Delete,
  PERMISSIONS.Promotions.Publish,
  PERMISSIONS.Coupons.View,
  PERMISSIONS.Coupons.Create,
  PERMISSIONS.Coupons.Edit,
  PERMISSIONS.Coupons.Delete,
  PERMISSIONS.Coupons.Generate,
  PERMISSIONS.Coupons.Export,
  PERMISSIONS.Coupons.Import,
  PERMISSIONS.Themes.View,
  PERMISSIONS.Themes.Create,
  PERMISSIONS.Themes.Edit,
  PERMISSIONS.Themes.Delete,
  PERMISSIONS.Themes.Publish,
  PERMISSIONS.Themes.Schedule,
  PERMISSIONS.Themes.Assign,
  PERMISSIONS.Themes.Export,
  PERMISSIONS.Themes.Import,
  PERMISSIONS.Themes.Rollback,
  PERMISSIONS.Legal.View,
  PERMISSIONS.Legal.Create,
  PERMISSIONS.Legal.Edit,
  PERMISSIONS.Legal.Publish,
  PERMISSIONS.Legal.Delete,
  PERMISSIONS.Suppliers.View,
  PERMISSIONS.Suppliers.Create,
  PERMISSIONS.Suppliers.Edit,
  PERMISSIONS.Suppliers.Delete,
  PERMISSIONS.Suppliers.ManageMappings,
  PERMISSIONS.Security.View,
  PERMISSIONS.Security.ManageUsers,
  PERMISSIONS.Security.ManageEmails,
  PERMISSIONS.Security.ManageCountries,
  PERMISSIONS.Security.ManageIPs,
  PERMISSIONS.Security.ViewEvents,
  PERMISSIONS.Security.ManageAlerts,
  PERMISSIONS.Security.ManageDevices,
  PERMISSIONS.Reviews.View,
  PERMISSIONS.Reviews.Moderate,
  PERMISSIONS.Notifications.View,
  PERMISSIONS.Notifications.Send,
  PERMISSIONS.Referral.View,
  PERMISSIONS.Referral.Manage,
  PERMISSIONS.Reports.View,
  PERMISSIONS.Reports.Export,
  PERMISSIONS.Reports.Schedule,
  PERMISSIONS.Reports.Delete,
  PERMISSIONS.Localization.Manage,
  PERMISSIONS.Settings.View,
  PERMISSIONS.Settings.Edit,
  PERMISSIONS.Support.View,
  PERMISSIONS.Support.Manage,
  PERMISSIONS.Support.Create,
  PERMISSIONS.Support.Reply,
  PERMISSIONS.Support.Assign,
  PERMISSIONS.Support.Close,
  PERMISSIONS.Support.Delete,
  PERMISSIONS.Support.ManageCategories,
  PERMISSIONS.Support.ManageSavedReplies,
  PERMISSIONS.Support.ManageKnowledgeBase,
  PERMISSIONS.Support.ViewAnalytics,
  PERMISSIONS.Media.Upload,
  PERMISSIONS.Media.Delete,
  PERMISSIONS.AuditLogs.View,
  PERMISSIONS.Operations.View,
  PERMISSIONS.Operations.Manage,
  PERMISSIONS.Operations.Retry,
  PERMISSIONS.Operations.Export,
  PERMISSIONS.Operations.Clear,
  PERMISSIONS.Analytics.View,
  PERMISSIONS.Analytics.Export,
  PERMISSIONS.Analytics.Compare,
  PERMISSIONS.Analytics.Manage,
  PERMISSIONS.Communication.View,
  PERMISSIONS.Communication.Manage,
  PERMISSIONS.Communication.Send,
  PERMISSIONS.Communication.ManageTemplates,
  PERMISSIONS.Communication.ManageProviders,
  PERMISSIONS.Faq.View,
  PERMISSIONS.Faq.Create,
  PERMISSIONS.Faq.Edit,
  PERMISSIONS.Faq.Delete,
  PERMISSIONS.Faq.Publish,
  PERMISSIONS.WhatsAppBot.View,
  PERMISSIONS.WhatsAppBot.Edit,
] as const;

export const OWNER_ROLE_NAMES = ['Owner', 'SuperAdmin', 'Admin', 'Administrator'] as const;

export const ADMIN_AREA_PREFIXES = [
  'Dashboard.',
  'Catalog.',
  'Roles.',
  'Orders.',
  'Customers.',
  'Users.',
  'Permissions.',
  'Memberships.',
  'Promotions.',
  'Coupons.',
  'Themes.',
  'Legal.',
  'Suppliers.',
  'Security.',
  'Reviews.',
  'Notifications.',
  'Referral.',
  'Reports.',
  'Localization.',
  'Settings.',
  'Support.',
  'Media.',
  'AuditLogs.',
  'Operations.',
  'Analytics.',
  'Communication.',
  'Faq.',
  'WhatsAppBot.',
] as const;

export function isAdminAccessPermission(permission: string): boolean {
  return ADMIN_AREA_PREFIXES.some((prefix) => permission.startsWith(prefix));
}
